# Generated by Django 5.2.1 on 2025-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_car', models.CharField(max_length=100)),
                ('fecha_creacion_car', models.DateTimeField(auto_now_add=True)),
                ('telefono_car', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
